apiVersion: apps/v1
kind: Deployment
metadata:
  name: erum_repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erum_repo
  template:
    metadata:
      labels:
        app: erum_repo
    spec:
      containers:
        - name: erum_repo
          image: erumfaiz/erum_repo:v1   # use your Docker Hub image
          ports:
            - containerPort: 5000
